<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBjWJzxh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBjWJzxh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBjWJzxh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBjWJzxh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBjWJzxh\App_KernelDevDebugContainer([
    'container.build_hash' => 'BjWJzxh',
    'container.build_id' => 'f2c0a75d',
    'container.build_time' => 1707233425,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBjWJzxh');
